apiVersion: apps/v1
kind: Deployment
metadata:
  name: heimdall-hubot-deployment
  labels:
    app: hubot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hubot
  template:
    metadata:
      labels:
        app: hubot
    spec:
      containers:
        - name: hubot
          # image: gcr.io/cfc-production/heimdall:USE_CIRCLE_CI_BUILDS
          env:
            - name: HUBOT_CIRCLECI_TOKEN
              valueFrom:
                secretKeyRef:
                  name: heimdall-hubot
                  key: circle_ci_token
            - name: HUBOT_FLOWDOCK_API_TOKEN
              valueFrom:
                secretKeyRef:
                  name: heimdall-hubot
                  key: flowdock_token
            - name: HUBOT_HOST
              valueFrom:
                secretKeyRef:
                  name: heimdall-hubot
                  key: host
            - name: RELEASE_NOTIFICATION_ROOM
              valueFrom:
                secretKeyRef:
                  name: heimdall-hubot
                  key: heimdall_alert_flow
            - name: SUGGESTION_ALERT_ROOM
              valueFrom:
                secretKeyRef:
                  name: heimdall-hubot
                  key: heimdall_alert_flow
            - name: REDIS_URL
              value: $(HEIMDALL_REDIS_SERVICE_PORT)
            - name: GITHUB_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: heimdall-hubot
                  key: github_client_id
            - name: GITHUB_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: heimdall-hubot
                  key: github_client_secret
            - name: IMGFLIP_API_USERNAME
              valueFrom:
                secretKeyRef:
                  name: heimdall-hubot
                  key: imgflip_api_username
            - name: IMGFLIP_API_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: heimdall-hubot
                  key: imgflip_api_password
            - name: ZEPLIN_FLOWDOCK_TOKEN
              valueFrom:
                secretKeyRef:
                  name: heimdall-hubot
                  key: zeplin_flowdock_token
            - name: ZEPLIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: heimdall-hubot
                  key: zeplin_username
            - name: ZEPLIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: heimdall-hubot
                  key: zeplin_password
            - name: ZOOM_API_KEY
              valueFrom:
                secretKeyRef:
                  name: heimdall-hubot
                  key: zoom_api_key
            - name: ZOOM_API_SECRET
              valueFrom:
                secretKeyRef:
                  name: heimdall-hubot
                  key: zoom_api_secret
            - name: ZOOM_MEETING_DURATION
              value: 60
          ports:
            - containerPort: 8080
          resources:
            limits:
              cpu: "0.1"
