name: Build

on:
  pull_request: {}
  push:
    branches:
    - main
    tags:
    - v*

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Read .nvmrc
      run: echo "NVMRC=$(cat ./.nvmrc)" > $GITHUB_OUTPUT
      id: nvm
    - name: Use Node + Yarn
      uses: actions/setup-node@v3
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
        cache: "yarn"
    - run: yarn install --frozen-lockfile
    - run: yarn test

  build-and-push-image:
    needs: test
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Read .nvmrc
      run: echo "NVMRC=$(cat ./.nvmrc)" > $GITHUB_OUTPUT
      id: nvm
    - name: Use Node + Yarn
      uses: actions/setup-node@v3
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
        cache: "yarn"
    - run: yarn install --frozen-lockfile
    - name: Build docker image
      run: |
        echo $GITHUB_SHA > BUILD
        docker build . -f infrastructure/docker/Dockerfile -t gcr.io/thesis-ops-2748/valkyrie:$GITHUB_SHA
    - name: Authenticate push with GCP
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      id: 'auth-push'
      uses: 'google-github-actions/auth@v0'
      with:
        credentials_json: '${{ secrets.GCP_GCR_CREDENTIALS }}'
    - name: Set up GCP tools
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      uses: google-github-actions/setup-gcloud@v0
    - name: Push docker image to GCP
      if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
      run: |
        # Set up docker to authenticate via gcloud command-line tool.
        gcloud auth configure-docker
        docker push gcr.io/thesis-ops-2748/valkyrie:${{ github.sha }}

  deploy:
    if: github.ref == 'refs/heads/main' || startsWith(github.ref, 'refs/tags/')
    needs: build-and-push-image
    uses: ./.github/workflows/deploy.yml
    with:
      docker-image-name: valkyrie
      docker-image-version: ${{ github.sha }}
      gcp-project-name: thesis-ops
      gcp-project-id: thesis-ops-2748
    secrets:
      GCP_DEPLOY_CREDENTIALS: ${{ secrets.GCP_DEPLOY_CREDENTIALS }}

  lint:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Read .nvmrc
      run: echo "NVMRC=$(cat ./.nvmrc)" > $GITHUB_OUTPUT
      id: nvm
    - name: Use Node + Yarn
      uses: actions/setup-node@v3
      with:
        node-version: "${{ steps.nvm.outputs.NVMRC }}"
        cache: "yarn"
    - run: yarn install --frozen-lockfile
    - run: yarn lint
